### ISSUE TITLE
[BUG] Document-features not compatible with vendored sources

### ISSUE THREAD

**Issue by LeoWherle** [Atmelfan/scpi-rs#26]
**Description**
When building a project using vendored sources, the Cargo.toml file is stripped of comments wich makes it impossible to build.

**To Reproduce**
Create a new project with the `{project-root}/.cargo/config.toml` file containing:
```toml
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
```
execute the following commands :
```
cargo vendor
cargo build
```

**Expected behavior**
The compilation of scpi fails.
````
error: Could not find documented features in Cargo.toml
  --> {project-root}/vendor/scpi/src/lib.rs:31:10
  ````

**Library and tool versions:**
 - scpi version:  1.0.0
 - rust version: 1.70.0 (90c541806 2023-05-31)
 - cargo version: 1.70.0 (ec8a8a0ca 2023-04-25)

**Additional context**
Currently I am getting around it by duplicating the Cargo.toml from github and renaming it to Cargo.toml.orig (and putting it next to the vendored Cargo.toml)
```
curl -o vendor/scpi/Cargo.toml.orig https://raw.githubusercontent.com/Atmelfan/scpi-rs/master/scpi/Cargo.toml
curl -o vendor/scpi-contrib/Cargo.toml.orig https://raw.githubusercontent.com/Atmelfan/scpi-rs/master/scpi/Cargo.toml
```

**Comment by LeoWherle** [comment]
I tried to implement the follwing fix proposed by document-features without success: https://docs.rs/document-features/latest/document_features/#compatibility as this just disables document-feature all-together if the doc is not built with `--all-features`

**Comment by Atmelfan** [comment]
Sorry for the late reply.

I wouldn't mind removing the document-features dependency altogether.

I am currently quite busy though so it'll probably take a while before I get to it.

**Comment by MatthieuDartiailh** [comment]
It appears that document-features 0.2.8 does not complain anymore when no documentation can be extracted from Cargo.toml (https://github.com/slint-ui/document-features/issues/20#issuecomment-1871821886). I will check on @LeoWherle system next week and confirm if it now works as expected.

**Comment by Atmelfan** [comment]
Is this still an issue @LeoWherle / @MatthieuDartiailh or can I close it?

**Comment by MatthieuDartiailh** [comment]
I finally managed to check and this can indeed be closed.
